Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ACorp.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ACorp.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Login.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using ACorp.Application;
using ACorp.Data;
using ACorp.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ACorp.Pages;

public class LoginModel : PageModel
{
    const string AuthenticationType = "CookieAuth";

    [BindProperty]
    public Credential Credential { get; set; }

    private readonly ILogger<LoginModel> _logger;
    private readonly ApplicationDbContext _db;
    private readonly AuthService _authService;

    public LoginModel(ApplicationDbContext db, ILogger<LoginModel> logger)
    {
        _db = db;
        _logger = logger;
        _authService = new AuthService(_db);
    }

    public void OnGet()
    {

    }

    public async Task<IActionResult> OnPostLoginAsync()
    {
        if (!ModelState.IsValid) return Page();

        if (await _authService.LoginAsync(Credential.Email, Credential.Password, HttpContext))
        {
            return RedirectToPage("/dashboard/index");
        }

        return Page();
    }
}

public class Credential
{
    [Required]
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; } = "";

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; } = "";
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ACorp.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Register.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text;
using ACorp.Application;
using ACorp.Data;
using ACorp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ACorp.Pages;

public class RegisterModel : PageModel
{
    [BindProperty]
    public RegisterForm RegisterForm { get; set; }
    [BindProperty]
    public string? Email { get; set; } = null;

    private readonly ILogger<RegisterModel> _logger;
    private readonly ApplicationDbContext _db;
    private readonly AuthService _authService;

    public RegisterModel(ApplicationDbContext db, ILogger<RegisterModel> logger)
    {
        _db = db;
        _logger = logger;
        _authService = new AuthService(_db);
    }

    public void OnPostEmail()
    {
        Email = RegisterForm.Email;
    }

    public async Task<IActionResult> OnPostRegisterAsync(string email)
    {
        RegisterForm.Email = email;
        User newUser = new()
        {
            Fullname = RegisterForm.FullName,
            Email = RegisterForm.Email,
            AesPassword = CryptoService.EncryptAESFromString(RegisterForm.Password),
            DesPassword = CryptoService.EncryptDESFromString(RegisterForm.Password),
            Rc4Password = CryptoService.EncryptRC4FromString(RegisterForm.Password),
            AesPhoneNumber = CryptoService.EncryptAESFromString(RegisterForm.PhoneNumber),
            DesPhoneNumber = CryptoService.EncryptDESFromString(RegisterForm.PhoneNumber),
            Rc4PhoneNumber = CryptoService.EncryptRC4FromString(RegisterForm.PhoneNumber),
            AesNik = CryptoService.EncryptAESFromString(RegisterForm.NIK),
            DesNik = CryptoService.EncryptDESFromString(RegisterForm.NIK),
            Rc4Nik = CryptoService.EncryptRC4FromString(RegisterForm.NIK),
        };

        if (!await _authService.RegisterAsync(newUser)) return RedirectToPage("/register");
        if (!await _authService.LoginAsync(email, RegisterForm.Password, HttpContext)) return RedirectToPage("/index");

        return RedirectToPage("/dashboard/index");
    }

    public void OnGet()
    {
    }
}

public class RegisterForm
{
    [Required]
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; } = "";

    [Required]
    [StringLength(maximumLength: 200, MinimumLength = 5)]
    public string FullName { get; set; } = "";

    [Required]
    public string Gender { get; set; } = "";

    [Required]
    [DataType(DataType.PhoneNumber)]
    public string PhoneNumber { get; set; } = "";

    [Required]
    public string NIK { get; set; } = "";

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; } = "";

    [Compare("Password", ErrorMessage = "Confirm password doesn't match")]
    public string ConfirmPassword { get; set; } = "";
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand fs-1 fw-bold me-5" asp-area="" asp-page="/Index">A</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1 justify-content-between mx-lg-5 px-lg-5">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/AboutUs">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/AboutUs">Daftarkan Dirimu</a>
                </li>
            </ul>
            <ul class="navbar-nav flex-grow-1 justify-content-between mx-lg-5 px-lg-5">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/Login">Login</a>
                </li>
                <a asp-area="" asp-page="/Register"><button type="button" class="btn btn-primary px-4 py-2 bg-primary-color">Register</button></a>
            </ul>
        </div>
    </div>
</nav>

<div style="height: 800px">
    <div id="hero-image" class="background">
        <div class="text-left d-flex align-items-center" style="height: 100%">
            <div class="container mb-5">
                <div class="col-6">
                    <h1 class="display-1 text-white fw-bold">Journey Start <span class="text-primary-color">From Here</span></h1>
                    <p class="text-white mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Ut enim ad minim veniam, quis nostrud exercitation </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="height: 500px">
    <div class="text-left d-flex align-items-center" style="height: 100%">
        <div class="container">
            <div class="col-6">
                <h1 class="display-2 fw-bold"><span class="text-primary-color">A Corp</span></h1>
                <p class="mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Ut enim ad minim veniam, quis nostrud exercitation </p>
            </div>
        </div>
    </div>
</div>
<div style="height: 800px">
    <div id="register-image" class="background">
        <div class="text-left d-flex align-items-center" style="height: 100%">
            <div class="container">
                <div class="col-6">
                    <h1 class="display-1 fw-bold"><span class="text-primary-color">Daftarkan Dirimu</span></h1>
                    <p class="text-white mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore Ut enim ad minim veniam, quis nostrud exercitation </p>
                    <button type="button" class="btn btn-primary px-4 py-2">Register</button>
                </div>
            </div>
        </div>
    </div>
</div>

Pages/Login.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}

<div class="row m-0">
    <div class="col-6 p-5">
        <div class="container">
            <h1 class="text-primary-color mb-5">Log In</h1>
            <form asp-page-handler="login" method="post">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <div class="mb-3">
                    <label for="inputEmail" asp-for="Credential.Email" class="text-primary-color">Email</label>
                    <input type="email" class="form-control" asp-for="Credential.Email" id="inputEmail"
                        aria-describedby="emailHelp">
                    <span class="text-danger" asp-validation-for="Credential.Email"></span>
                </div>
                <div class="mb-5">
                    <label for="inputPassword1" asp-for="Credential.Password"
                        class="form-label text-primary-color">Password</label>
                    <input type="password" asp-for="Credential.Password" class="form-control" id="inputPassword1">
                    <span class="text-danger" asp-validation-for="Credential.Password"></span>
                </div>
                <button type="submit" class="btn btn-primary py-2 d-flex justify-content-center mb-5"
                    style="width: 100%;">
                    Log In
                </button>
            </form>
            <div class="mb-4 d-flex justify-content-center">
                <div class="flex-grow-1">
                    <hr>
                </div>
                <p class="m-0 mt-1 mx-1 p-0">Atau</p>
                <div class="flex-grow-1">
                    <hr>
                </div>
            </div>
            <button type="button"
                class="btn border bg-transparent py-2 d-flex align-items-center justify-content-center"
                style="width: 100%">
                <svg class="me-3" xmlns="http://www.w3.org/2000/svg" width="31" height="30" viewBox="0 0 31 30"
                    fill="none">
                    <path
                        d="M28.1654 12.5519H27.125V12.5H15.5V17.5H22.7999C21.7349 20.4106 18.8732 22.5 15.5 22.5C11.2201 22.5 7.75001 19.1419 7.75001 15C7.75001 10.8581 11.2201 7.5 15.5 7.5C17.4756 7.5 19.273 8.22125 20.6415 9.39937L24.295 5.86375C21.9881 3.78312 18.9023 2.5 15.5 2.5C8.36678 2.5 2.58334 8.09688 2.58334 15C2.58334 21.9031 8.36678 27.5 15.5 27.5C22.6332 27.5 28.4167 21.9031 28.4167 15C28.4167 14.1619 28.3276 13.3438 28.1654 12.5519Z"
                        fill="#FFC107" />
                    <path
                        d="M4.07263 9.18188L8.3164 12.1938C9.46469 9.4425 12.2457 7.5 15.5 7.5C17.4756 7.5 19.273 8.22125 20.6415 9.39937L24.295 5.86375C21.9881 3.78312 18.9023 2.5 15.5 2.5C10.5387 2.5 6.23617 5.21062 4.07263 9.18188Z"
                        fill="#FF3D00" />
                    <path
                        d="M15.5 27.4999C18.8364 27.4999 21.8679 26.2643 24.16 24.2549L20.1623 20.9812C18.8219 21.9677 17.184 22.5012 15.5 22.4999C12.1404 22.4999 9.28774 20.4268 8.21307 17.5337L4.00095 20.6743C6.13865 24.7224 10.4799 27.4999 15.5 27.4999Z"
                        fill="#4CAF50" />
                    <path
                        d="M28.1654 12.5519H27.125V12.5H15.5V17.5H22.7999C22.2904 18.8853 21.3728 20.0957 20.1603 20.9819L20.1623 20.9806L24.16 24.2544C23.8771 24.5031 28.4167 21.25 28.4167 15C28.4167 14.1619 28.3275 13.3438 28.1654 12.5519Z"
                        fill="#1976D2" />
                </svg>
                Sign in with Google
            </button>
        </div>
    </div>
    <div class="col-6 p-0">
        <img src="images/login.jpeg" width="100%" style="height: 100vh; object-fit: cover" />
    </div>
</div>

Pages/Register.cshtml
@page
@model RegisterModel
@{
    ViewData["Title"] = "Register";
}

@if (Model.Email == null)
{
    <div class="row m-0">
    <div class="col-6 p-5 mt-5">
        <div class="container">
            <h1 class="text-primary-color mb-5">Create an account</h1>
            <form asp-page-handler="email" method="post">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <div class="mb-5">
                    <label for="inputEmail" asp-for="RegisterForm.Email" class="text-primary-color">Email</label>
                    <input type="email" asp-for="RegisterForm.Email" class="form-control" id="inputEmail"
                        aria-describedby="emailHelp">
                    <span class="text-danger" asp-validation-for="RegisterForm.Email"></span>
                </div>
                <button type="submit" class="btn btn-primary py-2 d-flex justify-content-center mb-5"
                    style="width: 100%">Confirm</button>
            </form>
            <div class="mb-4 d-flex justify-content-center">
                <div class="flex-grow-1">
                    <hr>
                </div>
                <p class="m-0 mt-1 mx-1 p-0">Atau login dengan</p>
                <div class="flex-grow-1">
                    <hr>
                </div>
            </div>
            <button type="button"
                class="btn border bg-transparent py-2 d-flex align-items-center justify-content-center"
                style="width: 100%">
                <svg class="me-3" xmlns="http://www.w3.org/2000/svg" width="31" height="30" viewBox="0 0 31 30"
                    fill="none">
                    <path
                        d="M28.1654 12.5519H27.125V12.5H15.5V17.5H22.7999C21.7349 20.4106 18.8732 22.5 15.5 22.5C11.2201 22.5 7.75001 19.1419 7.75001 15C7.75001 10.8581 11.2201 7.5 15.5 7.5C17.4756 7.5 19.273 8.22125 20.6415 9.39937L24.295 5.86375C21.9881 3.78312 18.9023 2.5 15.5 2.5C8.36678 2.5 2.58334 8.09688 2.58334 15C2.58334 21.9031 8.36678 27.5 15.5 27.5C22.6332 27.5 28.4167 21.9031 28.4167 15C28.4167 14.1619 28.3276 13.3438 28.1654 12.5519Z"
                        fill="#FFC107" />
                    <path
                        d="M4.07263 9.18188L8.3164 12.1938C9.46469 9.4425 12.2457 7.5 15.5 7.5C17.4756 7.5 19.273 8.22125 20.6415 9.39937L24.295 5.86375C21.9881 3.78312 18.9023 2.5 15.5 2.5C10.5387 2.5 6.23617 5.21062 4.07263 9.18188Z"
                        fill="#FF3D00" />
                    <path
                        d="M15.5 27.4999C18.8364 27.4999 21.8679 26.2643 24.16 24.2549L20.1623 20.9812C18.8219 21.9677 17.184 22.5012 15.5 22.4999C12.1404 22.4999 9.28774 20.4268 8.21307 17.5337L4.00095 20.6743C6.13865 24.7224 10.4799 27.4999 15.5 27.4999Z"
                        fill="#4CAF50" />
                    <path
                        d="M28.1654 12.5519H27.125V12.5H15.5V17.5H22.7999C22.2904 18.8853 21.3728 20.0957 20.1603 20.9819L20.1623 20.9806L24.16 24.2544C23.8771 24.5031 28.4167 21.25 28.4167 15C28.4167 14.1619 28.3275 13.3438 28.1654 12.5519Z"
                        fill="#1976D2" />
                </svg>
                Sign in with Google
            </button>
        </div>
    </div>
    <div class="col-6 p-0">
        <img src="images/login.jpeg" width="100%" style="height: 100vh; object-fit: cover" />
    </div>
</div>
}
else
{
    <div class="container mt-5">
    <button class="bg-transparent border-0 d-flex align-items-center">
        <a asp-area="" asp-page="/Register" class="text-body p-0 m-0" style="text-decoration: none;">
            <svg class="me-2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M20 11H7.83L13.42 5.41L12 4L4 12L12 20L13.41 18.59L7.83 13H20V11Z" fill="#231F20" />
            </svg>
            Kembali
        </a>
    </button>
    <div class="p-4 m-5 border mx-auto" style="max-width: 880px;">
        <h2 class="text-primary-color mb-5">Create Account</h2>
        <hr>
        <form asp-page-handler="register" method="post">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <input type="hidden" name="email" value=@Model.Email />
            <div class="mb-3">
                <label for="inputName" asp-for="RegisterForm.FullName"
                    class="form-label text-primary-color">Nama</label>
                <input type="text" asp-for="RegisterForm.FullName" class="form-control" id="inputName">
                <span class="text-danger" asp-validation-for="RegisterForm.FullName"></span>
            </div>
            <div class="mb-3">
                <label class="form-label text-primary-color" style="display: block">Jenis Kelamin</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" asp-for="RegisterForm.Gender" value="Male"
                        id="lakilaki" checked>
                    <label class="form-check-label" asp-for="RegisterForm.Gender" for="lakilaki">
                        Laki-laki
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" asp-for="RegisterForm.Gender" value="Female"
                        id="perempuan">
                    <label class="form-check-label" asp-for="RegisterForm.Gender" for="perempuan">
                        Perempuan
                    </label>
                </div>
                <span class="text-danger" asp-validation-for="RegisterForm.Gender"></span>
            </div>
            <div class="mb-3">
                <label for="inputNoHP" asp-for="RegisterForm.PhoneNumber" class="form-label text-primary-color">Nomor
                    HP</label>
                <input type="text" asp-for="RegisterForm.PhoneNumber" class="form-control" id="inputNoHP">
                <span class="text-danger" asp-validation-for="RegisterForm.PhoneNumber"></span>
            </div>
            <div class="mb-3">
                <label for="inputNIK" asp-for="RegisterForm.NIK" class="form-label text-primary-color">NIK</label>
                <input type="text" asp-for="RegisterForm.NIK" class="form-control" id="inputNIK">
                <span class="text-danger" asp-validation-for="RegisterForm.NIK"></span>
            </div>
            <div class="mb-3">
                <label for="inputPassword" asp-for="RegisterForm.Password"
                    class="form-label text-primary-color">Password</label>
                <input type="password" asp-for="RegisterForm.Password" class="form-control" id="inputPassword">
                <span class="text-danger" asp-validation-for="RegisterForm.Password"></span>
            </div>
            <div class="mb-5">
                <label for="inputKonfirmasiPassword" asp-for="RegisterForm.ConfirmPassword"
                    class="form-label text-primary-color">Konfirmasi Password</label>
                <input type="password" asp-for="RegisterForm.ConfirmPassword" class="form-control"
                    id="inputKonfirmasiPassword">
                <span class="text-danger" asp-validation-for="RegisterForm.ConfirmPassword"></span>
            </div>
            <button type="submit" class="btn btn-primary px-4 py-2">Daftar</button>
        </form>
    </div>
</div>
}