Pages/Dashboard/Account.cshtml.cs
using System.Security.Claims;
using System.Text.RegularExpressions;
using ACorp.Application;
using ACorp.Data;
using ACorp.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Crypto.Parameters;

namespace ACorp.Pages.Dashboard;

[Authorize]
public class AccountModel : PageModel
{
    public string? Name { get; set; } = "";
    public string? Email { get; set; } = "";
    public string? PhoneNumber { get; set; } = "";
    public string? NIK { get; set; } = "";
    public string? Key { get; set; } = "";

    private readonly ILogger<AccountModel> _logger;
    private readonly ApplicationDbContext _db;

    public AccountModel(ILogger<AccountModel> logger, ApplicationDbContext db)
    {
        _logger = logger;
        _db = db;
    }

    public void OnGet()
    {
        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        Name = claimsIdentity?.FindFirst(ClaimTypes.Name)?.Value;
        Email = claimsIdentity?.FindFirst(ClaimTypes.Email)?.Value;
        var user = _db.Users.FirstOrDefault(u => u.Email == Email);
        NIK = CryptoService.DecryptAESFromString(user?.AesNik!);
        PhoneNumber = CryptoService.DecryptDESFromString(user?.DesPhoneNumber!);
        Key = user?.SymmetricKey;

        // var user = _db.Users.FirstOrDefault(u => u.Email == Email);
        // PhoneNumber = _cryptoService.DecryptAESFromString(user.AesPhoneNumber);
    }

    public async Task<IActionResult> OnPostAsync()
    {
        // generate symmetric key
        var symmetricKeyByte = Cryptography.KeyParameterGeneration(128);
        var symmetricKeyString = Convert.ToBase64String(symmetricKeyByte);

        // generate RSA keys
        var (publicKey, privateKey) = Cryptography.GenerateRSAKeys();

        // encrypt symmetric key with RSA public key
        var encryptedSymmetricKey = Cryptography.EncryptWithRSA(symmetricKeyString, publicKey);

        // store the publicKey, privateKey, and encryptedSymmetricKey to database
        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        Email = claimsIdentity?.FindFirst(ClaimTypes.Email)?.Value;
        var user = _db.Users.FirstOrDefault(u => u.Email == Email);
        if (user == null)
        {
            return RedirectToPage("/Login");
        }
        user.SymmetricKey = symmetricKeyString;
        user.RSAPublicKey = publicKey;
        user.RSAPrivateKey = privateKey;
        await _db.SaveChangesAsync();
        Key = encryptedSymmetricKey;

        return RedirectToPage("/Dashboard/Account");
    }
}

Pages/Dashboard/Check.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Text;
using ACorp.Application;
using ACorp.Data;
using ACorp.Models;
using ACorp.Shared;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ACorp.Pages;

[Authorize]
public class CheckModel : PageModel
{
    public IEnumerable<User> RequestedUsers { get; set; } = new List<User>();

    private readonly IWebHostEnvironment _environment;
    private readonly ILogger<CheckModel> _logger;
    private readonly ApplicationDbContext _db;
    private readonly AuthService _authService;
    private readonly RequestDataService _requestDataService;
    private readonly DocumentService _documentService;

    public CheckModel(IWebHostEnvironment environment, ApplicationDbContext db, ILogger<CheckModel> logger)
    {
        _environment = environment;
        _db = db;
        _logger = logger;
        _authService = new AuthService(_db);
        _requestDataService = new RequestDataService(_db);
        _documentService = new DocumentService(_environment, _db);
    }

    public async Task OnGetAsync()
    {
        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        var identityEmail = claimsIdentity?.FindFirst(ClaimTypes.Email)?.Value;

        User? requester = await _authService.FindUserAsync(identityEmail ?? "");

        if (requester == null) return;

        RequestedUsers = await _requestDataService.GetAllRequestedUserAsync(requester);
    }

    public async Task<IActionResult> OnPostRequestCheckAsync(string email)
    {
        User? UserToRequest = await _authService.FindUserAsync(email);

        if (UserToRequest == null) return RedirectToPage("/dashboard/check");

        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        var identityEmail = claimsIdentity?.FindFirst(ClaimTypes.Email)?.Value;

        if (UserToRequest.Email == identityEmail) return RedirectToPage("/dashboard/check");

        User? requester = await _authService.FindUserAsync(identityEmail ?? "");

        if (requester == null) return RedirectToPage("/dashboard/check");

        await _requestDataService.Request(requester, UserToRequest);

        return RedirectToPage("/dashboard/check");
    }

    public async Task<IActionResult> OnPostKtpAsync(int id, string key)
    {
        _logger.LogInformation("key: " + key);

        User? user = await GetCurrentUserAsync();
        if (user == null) return NotFound();

        User? requestedUser = await _authService.FindUserAsync(id);
        if (requestedUser == null) return NotFound();

        if (user.RSAPrivateKey == null) throw new ApplicationException("User with id: " + user.Id + " doesn't have private key");
        var docKey = Cryptography.DecryptWithRSA(key, user.RSAPrivateKey);
        if (docKey != requestedUser.SymmetricKey) throw new ApplicationException("Wrong key.");
        var (decryptedFile, fileName) = await _documentService.DownloadAsync(requestedUser, docKey, DocumentType.KTP);

        return File(decryptedFile, "application/octet-stream", fileName);
    }

    public async Task<IActionResult> OnPostCvAsync(int id, string key)
    {
        User? user = await GetCurrentUserAsync();
        if (user == null) return NotFound();

        User? requestedUser = await _authService.FindUserAsync(id);
        if (requestedUser == null) return NotFound();

        if (user.RSAPrivateKey == null) throw new ApplicationException("User with id: " + user.Id + " doesn't have private key");
        var docKey = Cryptography.DecryptWithRSA(key, user.RSAPrivateKey);
        if (docKey != requestedUser.SymmetricKey) throw new ApplicationException("Wrong key.");
        var (decryptedFile, fileName) = await _documentService.DownloadAsync(requestedUser, docKey, DocumentType.CV);

        return File(decryptedFile, "application/octet-stream", fileName);
    }

    public async Task<IActionResult> OnPostVideoAsync(int id, string key)
    {
        User? user = await GetCurrentUserAsync();
        if (user == null) return NotFound();

        User? requestedUser = await _authService.FindUserAsync(id);
        if (requestedUser == null) return NotFound();

        if (user.RSAPrivateKey == null) throw new ApplicationException("User with id: " + user.Id + " doesn't have private key");
        var docKey = Cryptography.DecryptWithRSA(key, user.RSAPrivateKey);
        if (docKey != requestedUser.SymmetricKey) throw new ApplicationException("Wrong key.");
        var (decryptedFile, fileName) = await _documentService.DownloadAsync(requestedUser, docKey, DocumentType.Video);

        return File(decryptedFile, "application/octet-stream", fileName);
    }

    async Task<User?> GetCurrentUserAsync()
    {
        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        var userEmail = claimsIdentity?.FindFirst(ClaimTypes.Email)?.Value;
        if (userEmail == null) return null;
        return await _authService.FindUserAsync(userEmail);
    }
}

Pages/Dashboard/Download.cshtml.cs
using ACorp.Data;
using ACorp.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using ACorp.Shared;
using System.Text;
using ACorp.Application;


namespace ACorp.Pages.Dashboard;

[Authorize]
public class DownloadModel : PageModel
{
    private readonly IWebHostEnvironment _environment;
    private readonly ApplicationDbContext _db;
    private readonly AuthService _authService;
    private readonly DocumentService _documentService;

    public string? KTP { get; set; } = "";
    public string? CV { get; set; } = "";
    public string? Video { get; set; } = "";

    public DownloadModel(IWebHostEnvironment environment, ApplicationDbContext db)
    {
        _environment = environment;
        _db = db;
        _authService = new AuthService(_db);
        _documentService = new DocumentService(_environment, _db);
    }

    public void OnGet()
    {
        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        var userData = _db.Users.FirstOrDefault(u => u.Email == claimsIdentity!.FindFirst(ClaimTypes.Email)!.Value);
        var ktpDoc = userData != null ? _db.Documents.FirstOrDefault(d => d.UserId == userData.Id && d.Type == "ID_CARD") : null;
        KTP = ktpDoc?.Name + ktpDoc?.FileExtension;

        var cvDoc = userData != null ? _db.Documents.FirstOrDefault(d => d.UserId == userData.Id && d.Type == "CV") : null;
        CV = cvDoc?.Name + cvDoc?.FileExtension;

        var videoDoc = userData != null ? _db.Documents.FirstOrDefault(d => d.UserId == userData.Id && d.Type == "VIDEO") : null;
        Video = videoDoc?.Name + videoDoc?.FileExtension;
    }

    public async Task<IActionResult> OnPostKtpAsync()
    {
        User? user = await GetCurrentUserAsync();
        if (user == null) return NotFound();

        if (user.SymmetricKey == null) throw new ApplicationException("User with id: " + user.Id + " doesn't have symmetric key.");
        var (decryptedFile, fileName) = await _documentService.DownloadAsync(user, user.SymmetricKey, DocumentType.KTP);

        return File(decryptedFile, "application/octet-stream", fileName);
    }

    public async Task<IActionResult> OnPostCv()
    {
        User? user = await GetCurrentUserAsync();
        if (user == null) return NotFound();

        if (user.SymmetricKey == null) throw new ApplicationException("User with id: " + user.Id + " doesn't have symmetric key.");
        var (decryptedFile, fileName) = await _documentService.DownloadAsync(user, user.SymmetricKey, DocumentType.CV);

        return File(decryptedFile, "application/octet-stream", fileName);
    }

    public async Task<IActionResult> OnPostVideo()
    {
        User? user = await GetCurrentUserAsync();
        if (user == null) return NotFound();

        if (user.SymmetricKey == null) throw new ApplicationException("User with id: " + user.Id + " doesn't have symmetric key.");
        var (decryptedFile, fileName) = await _documentService.DownloadAsync(user, user.SymmetricKey, DocumentType.Video);

        return File(decryptedFile, "application/octet-stream", fileName);
    }

    async Task<User?> GetCurrentUserAsync()
    {
        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        var userEmail = claimsIdentity?.FindFirst(ClaimTypes.Email)?.Value;
        if (userEmail == null) return null;
        return await _authService.FindUserAsync(userEmail);
    }

}

Pages/Dashboard/File.cshtml.cs
using System.Security.Claims;
using System.Text;
using ACorp.Application;
using ACorp.Data;
using ACorp.Models;
using ACorp.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ACorp.Pages.Dashboard;

[Authorize]
public class FileModel : PageModel
{
    private readonly IWebHostEnvironment _environment;
    private readonly ApplicationDbContext _db;
    private readonly DocumentService _documentService;

    [BindProperty]
    public IFormFile Upload { get; set; }

    [BindProperty]
    public string FileType { get; set; }
    public FileModel(IWebHostEnvironment environment, ApplicationDbContext db)
    {
        _environment = environment;
        _db = db;
        _documentService = new(_environment, _db);
    }

    public void OnGet()
    {
        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        var userEmail = claimsIdentity?.FindFirst(ClaimTypes.Email)?.Value;
        var userId = _db.Users.FirstOrDefault(u => u.Email == userEmail)?.Id;
        var idCards = _db.Documents.Where(d => d.UserId == userId).Where(d => d.Type == "ID_CARD");
        var Cvs = _db.Documents.Where(d => d.UserId == userId).Where(d => d.Type == "CV");
        var videos = _db.Documents.Where(d => d.UserId == userId).Where(d => d.Type == "VIDEO");
    }

    public async Task OnPostAsync()
    {
        ClaimsIdentity? claimsIdentity = User.Identity as ClaimsIdentity;
        var userEmail = claimsIdentity?.FindFirst(ClaimTypes.Email)?.Value;
        var user = _db.Users.FirstOrDefault(u => u.Email == userEmail);
        if (user == null) return;

        var fileId = Guid.NewGuid().ToString();
        var fileExtension = Path.GetExtension(Upload.FileName);

        // remove previous file
        var prevDoc = _db.Documents.FirstOrDefault(d => d.UserId == user.Id && d.FileExtension == fileExtension);
        if (prevDoc != null)
        {
            String[] subPaths = new String[] { "aes", "des", "rc4" };
            foreach (String subPath in subPaths)
            {
                var prevFilePath = Path.Combine(_environment.ContentRootPath, "Storage", subPath, prevDoc.Name);
                if (System.IO.File.Exists(prevFilePath))
                {
                    System.IO.File.Delete(prevFilePath);
                }
            }
            _db.RemoveRange(_db.Documents.Where(d => d.Name == prevDoc.Name).ToList());

        }

        var myAesKey = Encoding.UTF8.GetBytes("ThisIsAKeyForAES");
        var myAesIv = Encoding.UTF8.GetBytes("ThisIVAKeyForAES");
        var myAeskeyParam = Cryptography.KeyParameterGenerationWithKeyAndIV(myAesKey, myAesIv);

        var myDesKey = Encoding.UTF8.GetBytes("KyForDES");
        var myDesIv = Encoding.UTF8.GetBytes("IvForDES");
        var myDeskeyParam = Cryptography.KeyParameterGenerationWithKeyAndIV(myDesKey, myDesIv);

        if (string.IsNullOrEmpty(user.SymmetricKey))
        {
            var myRc4KeyString = CryptoService.GetUniqueKey();
            user.SymmetricKey = myRc4KeyString;

            _db.Update(user);
            await _db.SaveChangesAsync();
        }

        // var myRc4Key = Encoding.UTF8.GetBytes("ThisIsMyRC4Key");
        if (user.SymmetricKey == null) throw new ApplicationException("User with id: " + user.Id + " doesn't have symmetric key.");
        var myRc4Key = Encoding.UTF8.GetBytes(user.SymmetricKey);
        var myRc4keyParam = Cryptography.KeyParameterGenerationWithKey(myRc4Key);

        using MemoryStream encryptionStream = new();
        await Upload.CopyToAsync(encryptionStream);
        var fileData = encryptionStream.ToArray();

        // encrypt with rc4
        DateTime startRc4 = DateTime.Now;
        var encryptedRc4File = Cryptography.Rc4Encrypt(myRc4keyParam, fileData);
        DateTime endRc4 = DateTime.Now;
        var encryptedRc4FilePath = Path.Combine(_environment.ContentRootPath, "Storage", "rc4", fileId);
        using var encryptedRc4FileStream = new FileStream(encryptedRc4FilePath, FileMode.Create);

        byte[] signedRc4File = await _documentService.AttachDigitalSignatureAsync(user, encryptedRc4File);

        encryptedRc4FileStream.Write(signedRc4File, 0, signedRc4File.Length);
        Document document3 = new()
        {
            Name = fileId,
            Cipher = "RC4",
            FileExtension = fileExtension,
            Type = FileType,
            UserId = user.Id,
            EncryptDuration = endRc4 - startRc4
        };
        await _db.Documents.AddAsync(document3);

        // encrypt with des cbc
        DateTime startDes = DateTime.Now;
        var encryptedDesFile = Cryptography.DesCbcPaddedEncrypt(myDeskeyParam, fileData);
        DateTime endDes = DateTime.Now;
        var encryptedDesFilePath = Path.Combine(_environment.ContentRootPath, "Storage", "des", fileId);
        using var encryptedDesFileStream = new FileStream(encryptedDesFilePath, FileMode.Create);

        byte[] signedDesFile = await _documentService.AttachDigitalSignatureAsync(user, encryptedDesFile);

        encryptedDesFileStream.Write(signedDesFile, 0, signedDesFile.Length);
        Document document2 = new()
        {
            Name = fileId,
            Cipher = "DES-64-CBC",
            FileExtension = fileExtension,
            Type = FileType,
            UserId = user.Id,
            EncryptDuration = endDes - startDes
        };
        await _db.Documents.AddAsync(document2);

        // encrypt with aes 128 cbc
        DateTime startAes = DateTime.Now;
        var encryptedAesFile = Cryptography.AesCbcPaddedEncrypt(myAeskeyParam, fileData);
        DateTime endAes = DateTime.Now;
        var encryptedAesFilePath = Path.Combine(_environment.ContentRootPath, "Storage", "aes", fileId);
        using var encryptedFileStream = new FileStream(encryptedAesFilePath, FileMode.Create);

        byte[] signedAesFile = await _documentService.AttachDigitalSignatureAsync(user, encryptedAesFile);

        encryptedFileStream.Write(signedAesFile, 0, signedAesFile.Length);
        Document document = new()
        {
            Name = fileId,
            Cipher = "AES-128-CBC",
            FileExtension = fileExtension,
            Type = FileType,
            UserId = user.Id,
            EncryptDuration = endAes - startAes
        };
        await _db.Documents.AddAsync(document);

        await _db.SaveChangesAsync();
    }
}

Pages/Dashboard/Check.cshtml
@page
@model CheckModel
@{
    ViewData["Title"] = "Check Data";
}

<h1 class="display-5 fw-bold mb-3">Check Data</h1>
<div class="card mb-4">
    <div class="card-header">
        <p class="fw-bold fs-3 m-0">Request Check Data</p>
    </div>
    <form class="card-body" method="post" asp-page-handler="RequestCheck">
        <p>Including Image and Documents</p>
        <input type="text" name="email" id="email" class="form-control" placeholder="Search by email" />
        <div class="d-flex align-items-center gap-3 border p-1 rounded">
            <button class="btn btn-primary">Request</button>
        </div>
    </form>
</div>

<div class="card mb-4">
    <div class="card-header">
        <p class="fw-bold fs-3 m-0">Available Data</p>
    </div>
    <div class="card-body">
        <div class="container">

            <div class="table">
                <div class="table-header">
                    <div class="header__item"><a id="name" class="filter__link" href="#">Name</a></div>
                    <div class="header__item"><a id="wins" class="filter__link filter__link--number" href="#">KTP</a>
                    </div>
                    <div class="header__item"><a id="draws" class="filter__link filter__link--number" href="#">CV</a>
                    </div>
                    <div class="header__item"><a id="losses" class="filter__link filter__link--number"
                            href="#">Video</a></div>
                </div>
                <div class="table-content">
                    @foreach (var user in Model.RequestedUsers)
                    {
                        <div class="table-row">
                            <div class="table-data" style="min-width: 25%; margin-top: auto; margin-bottom: auto;">
                                @user.Fullname</div>
                            @foreach (var handler in new[] { "Ktp", "Cv", "Video" })
                            {
                                <div class="table-data">
                                    <form asp-page-handler="@handler">
                                        <input type="hidden" name="id" value="@user.Id" />
                                        <div style="display: flex; flex-direction: column; align-items: stretch;">
                                            <input type="text" name="key" placeholder="Key"
                                                style="width: 100%; box-sizing: border-box; margin-bottom: 10px;" />
                                            <button class="btn btn-primary" type="submit" style="width: 100%;">Unduh</button>
                                        </div>
                                    </form>
                                </div>
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // Use jQuery to update the value of the shared input field
    $(document).ready(function () {
        var keyInput = $("#keyInput");

        // Listen for changes to the 'Key' property and update the input field
        keyInput.on("input", function () {
            keyInput.val($(this).val());
        });
    });
</script>

Pages/Dashboard/Download.cshtml
@page
@model DownloadModel
@{
    ViewData["Title"] = "Unduhan";
}

<h1 class="display-5 fw-bold mb-3">Unduhan</h1>
<div class="card mb-4">
    <div class="card-header">
        <p class="fw-bold fs-3 m-0">KTP</p>
    </div>
    <form class="card-body" method="post" asp-page-handler="Ktp">
        <p>Berikut adalah KTP yang telah terunggah</p>
        <div class="d-flex align-items-center gap-3 border p-1 rounded">
            <button class="btn btn-primary" type="submit">Unduh</button>
            <div>@Model.KTP</div>
        </div>
    </form>
</div>

<div class="card mb-4">
    <div class="card-header">
        <p class="fw-bold fs-3 m-0">CV</p>
    </div>
    <form class="card-body" method="post" asp-page-handler="Cv">
        <p>Berikut adalah CV yang telah terunggah</p>
        <div class="d-flex align-items-center gap-3 border p-1 rounded">
            <button class="btn btn-primary">Unduh</button>
            <div>@Model.CV</div>
        </div>
    </form>
</div>

<div class="card">
    <div class="card-header">
        <p class="fw-bold fs-3 m-0">Video</p>
    </div>
    <form class="card-body" method="post" asp-page-handler="Video">
        <p>Berikut adalah Video yang telah terunggah</p>
        <div class="d-flex align-items-center gap-3 border p-1 rounded">
            <button class="btn btn-primary">Unduh</button>
            <div>@Model.Video</div>
        </div>
    </form>
</div>

Pages/Dashboard/File.cshtml
@page
@model FileModel
@{
        ViewData["Title"] = "Berkas";
}

<h1 class="display-5 fw-bold mb-3">Berkas</h1>

<form class="card" method="post" enctype="multipart/form-data">
        <div class="card-header">
                <p class="fw-bold fs-3 m-0">Upload KTP</p>
        </div>
        <div class="card-body">
                <p>Silahkan upload KTP Anda dalam jpg, jpeg, atau png.</p>
                <input type="file" required asp-for="Upload" accept="image/png, image/jpeg, image/jpg" />
                <input type="text" required asp-for="FileType" value="ID_CARD" hidden />
        </div>
        <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>

<form class="card mt-3" method="post" enctype="multipart/form-data">
        <div class="card-header">
                <p class="fw-bold fs-3 m-0">Upload CV</p>
        </div>
        <div class="card-body">
                <p>Silahkan upload CV Anda dalam format doc, docx, atau pdf.</p>
                <input type="file" required asp-for="Upload" accept=".doc,.docs,.pdf" />
                <input type="text" required asp-for="FileType" value="CV" hidden />
        </div>
        <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>

<form class="card mt-3" method="post" enctype="multipart/form-data">
        <div class="card-header">
                <p class="fw-bold fs-3 m-0">Upload Video</p>
        </div>
        <div class="card-body">
                <p>Silahkan upload Video Anda</p>
                <input type="file" required asp-for="Upload" accept="video/*" />
                <input type="text" required asp-for="FileType" value="VIDEO" hidden />
        </div>
        <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>

Pages/Dashboard/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<h1 class="display-5 fw-bold mb-3">Welcome, @Model.Name</h1>
<div id="body-content" class="bg-white d-flex align-items-center justify-content-center">
    <button type="button" class="btn btn-primary px-4 py-2">File Upload</button>
</div>

Pages/Dashboard/Logout.cshtml
@page
@model LogoutModel
@{
    ViewData["Title"] = "Logout";
}